include(InstallRequiredSystemLibraries)

set(CPACK_PACKAGE_CONTACT makes.k.s@mail.ru)
set(CPACK_PACKAGE_VERSION ${PRINT_VERSION})
set(CPACK_PACKAGE_NAME "webpage_button")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "RK2 TIMP")
set(CPACK_PACKAGE_VENDOR "BeamzXD")
set(CPACK_PACKAGE_PACK_NAME "webpage_button-${PRINT_VERSION}")

set(CPACK_SOURCE_INSTALLED_DIRECTORIES 
	"${CMAKE_SOURCE_DIR}/webpage_button; webpage_button"
	"${CMAKE_SOURCE_DIR}/tests; tests")

set(CPACK_SOURCE_GENERATOR "TGZ;ZIP")

set(CPACK_DEBIAN_PACKAGE_VERSION ${PRINT_VERSION})
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "all")
set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "controls the fan")

set(CPACK_GENERATOR "DEB;RPM")

set(CPACK_RPM_PACKAGE_SUMMARY "controls the fan")

include(CPack)